platform :ios, '5.0'
pod 'AFNetworking', '~> 1.3.3'
pod 'MagicalRecord', '~> 2.2'
pod 'iVersion', '~> 1.10.6'
pod 'MBProgressHUD', '~> 0.8'
pod 'PSTCollectionView', '~> 1.2.0'
pod 'Reachability', '~> 3.1.1'